import { Category, MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Masala Dosa',
    description: 'Crispy rice crepe filled with spiced potato mash, served with coconut chutney and sambar.',
    price: 60,
    category: Category.SOUTH_INDIAN,
    imageUrl: 'public/images/dosa-1-1.jpg',
    isVeg: true,
  },
  {
    id: '2',
    name: 'Idli Vada ',
    description: 'Steamed rice cakes and crispy lentil donuts, the classic healthy breakfast.',
    price: 50,
    category: Category.SOUTH_INDIAN,
    imageUrl: 'public/images/shutterstock-326657696-cropped-1566550680.jpg', 
    isVeg: true,
  },
  {
    id: '3',
    name: 'Bisibele Bath ',
    description: 'a spiced, tangy, and comforting rice-lentil dish from Karnataka that warms the soul',
    price: 45,
    category: Category.SOUTH_INDIAN,
    imageUrl: 'public/images/bisibele.jpg', 
    isVeg: true,
  },

  {
    id: '3',
    name: 'Hyderabadi Biryani',
    description: 'Aromatic basmati rice cooked with fragrant spices and tender vegetables.',
    price: 120,
    category: Category.SOUTH_INDIAN, // Or generally Indian
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=600&auto=format&fit=crop',
    isSpicy: true,
    isVeg: true,
  },
  {
    id: '4',
    name: 'Butter Naan & Paneer',
    description: 'Soft tandoori bread served with rich and creamy paneer butter masala.',
    price: 150,
    category: Category.NORTH_INDIAN,
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=600&auto=format&fit=crop',
    isVeg: true,
  },
  {
    id: '5',
    name: 'Samosa Chat',
    description: 'Crushed samosa topped with chickpeas, yogurt, tangy tamarind chutney and spices.',
    price: 45,
    category: Category.SNACKS,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=600&auto=format&fit=crop',
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '6',
    name: 'Filter Coffee',
    description: 'Authentic South Indian filter coffee, strong and frothy.',
    price: 25,
    category: Category.BEVERAGES,
    imageUrl: 'public/images/filter-coffee.jpg',
    isVeg: true,
  },
  {
    id: '7',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry served with fried fluffy bread.',
    price: 100,
    category: Category.NORTH_INDIAN,
    imageUrl: 'public/images/puri-free-photo.jpg',
    isVeg: true,
    isSpicy: true,
  },
  {
    id: '8',
    name: 'Mango Lassi',
    description: 'Sweet and refreshing yogurt drink blended with ripe mango pulp.',
    price: 60,
    category: Category.BEVERAGES,
    imageUrl: 'public/images/Mango-Lassi-4.jpg',
    isVeg: true,
  },
   {
    id: '9',
    name: 'Gobi Fried Rice',
    description: 'Gobi Fried Rice is a flavorful Indo-Chinese dish made by stir-frying rice with spiced cauliflower florets, sauces, and aromatics',
    price: 80,
    category: Category.NORTH_INDIAN,
    imageUrl: 'public/images/gobifried.jpg',
    isVeg: true,
    isSpicy: true,
  },
   {
    id: '10',
    name: 'Bread Pakoda',
    description: 'a crispy, deep-fried snack made by stuffing spiced potato between bread slices and coating them in gram flour batter',
    price: 60,
    category: Category.SNACKS,
    imageUrl: 'public/images/pakoda.jpg',
    isVeg: true,
  },
   {
    id: '11',
    name: 'Kabab',
    description: 'a succulent, spiced meat or vegetable dish, grilled or roasted to smoky perfection',
    price: 110,
    category: Category.SOUTH_INDIAN,
    imageUrl: 'public/images/kabab.jpg',
    isVeg: false,
    isSpicy: true,
  },
];
